storage_account_name        = "testsa22062023"
publicip_name               = "test-pubip"
network_security_group_name = "test-nsg"
network_interface_name      = "test-nic"
virtual_machine_name        = "test-vm"
virtual_machine_size        = "Standard_Ds1_v2"
adminUser                   = "saanvikit"